import SwiftUI

/// A sheet for customizing goal appearance (icon and color).
///
/// **How It Works:**
/// - Presents icon picker (reuses GoalIconPicker) and color picker
/// - Changes are immediately reflected via bindings
/// - User taps "Done" to dismiss
///
/// **Usage:**
/// ```swift
/// .sheet(isPresented: $showAppearanceSheet) {
///     GoalAppearanceSheet(
///         selectedIcon: $selectedIcon,
///         selectedColor: $selectedColor,
///         autoGeneratedIcon: autoIcon
///     )
/// }
/// ```
struct GoalAppearanceSheet: View {
    @Binding var selectedIcon: String?
    @Binding var selectedColor: GoalPresetColor
    let autoGeneratedIcon: String

    @Environment(\.colorScheme) private var colorScheme
    @Environment(\.dismiss) private var dismiss

    var body: some View {
        NavigationStack {
            ScrollView {
                VStack(spacing: WinnieSpacing.xl) {
                    // Color picker (first)
                    colorPickerSection

                    // Icon picker (below color)
                    GoalIconPicker(
                        "Icon",
                        selectedIcon: $selectedIcon,
                        autoIcon: autoGeneratedIcon
                    )
                }
                .padding(.horizontal, WinnieSpacing.screenMarginMobile)
                .padding(.top, WinnieSpacing.l)
            }
            .background(WinnieColors.background(for: colorScheme))
            .navigationTitle("Customize Appearance")
            .navigationBarTitleDisplayMode(.inline)
            .toolbar {
                ToolbarItem(placement: .confirmationAction) {
                    Button("Done") {
                        dismiss()
                    }
                    .fontWeight(.semibold)
                    .foregroundStyle(WinnieColors.amethystSmoke)
                }
            }
        }
        .presentationDragIndicator(.visible)
        .presentationDetents([.medium, .large])
    }

    // MARK: - Color Picker Section

    private var colorPickerSection: some View {
        VStack(alignment: .leading, spacing: WinnieSpacing.s) {
            Text("Color")
                .font(WinnieTypography.bodyS())
                .fontWeight(.medium)
                .foregroundStyle(WinnieColors.secondaryText(for: colorScheme))

            LazyVGrid(columns: [GridItem](repeating: GridItem(.flexible(), spacing: 12), count: 4), spacing: 12) {
                ForEach(GoalPresetColor.allCases) { color in
                    ColorSwatch(
                        color: color,
                        isSelected: selectedColor == color,
                        onTap: { selectedColor = color }
                    )
                }
            }
        }
    }
}

// MARK: - Color Swatch Component

private struct ColorSwatch: View {
    let color: GoalPresetColor
    let isSelected: Bool
    let onTap: () -> Void

    @Environment(\.colorScheme) private var colorScheme

    var body: some View {
        Button(action: onTap) {
            ZStack {
                Circle()
                    .fill(color.color)
                    .frame(width: 52, height: 52)

                if isSelected {
                    Circle()
                        .strokeBorder(WinnieColors.primaryText(for: colorScheme), lineWidth: 3)
                        .frame(width: 52, height: 52)

                    Image(systemName: "checkmark")
                        .font(.system(size: 16, weight: .bold))
                        .foregroundStyle(WinnieColors.contrastText)
                }
            }
        }
        .buttonStyle(.plain)
        .accessibilityLabel(color.displayName)
        .accessibilityAddTraits(isSelected ? .isSelected : [])
    }
}

// MARK: - Previews

#Preview("Light Mode") {
    struct PreviewWrapper: View {
        @State private var selectedIcon: String? = nil
        @State private var selectedColor: GoalPresetColor = .amethyst

        var body: some View {
            GoalAppearanceSheet(
                selectedIcon: $selectedIcon,
                selectedColor: $selectedColor,
                autoGeneratedIcon: "house.fill"
            )
        }
    }
    return PreviewWrapper()
}

#Preview("Dark Mode") {
    struct PreviewWrapper: View {
        @State private var selectedIcon: String? = "airplane"
        @State private var selectedColor: GoalPresetColor = .sage

        var body: some View {
            GoalAppearanceSheet(
                selectedIcon: $selectedIcon,
                selectedColor: $selectedColor,
                autoGeneratedIcon: "house.fill"
            )
            .preferredColorScheme(.dark)
        }
    }
    return PreviewWrapper()
}

#Preview("With Selection") {
    struct PreviewWrapper: View {
        @State private var selectedIcon: String? = "heart.fill"
        @State private var selectedColor: GoalPresetColor = .rose

        var body: some View {
            GoalAppearanceSheet(
                selectedIcon: $selectedIcon,
                selectedColor: $selectedColor,
                autoGeneratedIcon: "star.fill"
            )
        }
    }
    return PreviewWrapper()
}
